export const defaults: Record<string, string> = {
  "site.logo": "",
  "home.hero.title": "Billistic Beaniez, FIRST LEGO League Robotics Team",
  "home.hero.subtitle": "Team #3818 | Perth, WA, Australia",
  "home.hero.description": "We are a student robotics team competing in FIRST LEGO League, combining engineering, programming, research and innovation to tackle real world challenges.",
  "home.hero.button1": "See Our Innovation",
  "home.hero.button2": "Meet Our Robot",
  "home.about.title": "About Billistic Beaniez",
  "home.about.desc": "Billistic Beaniez is FIRST LEGO League Team #3818, based in Perth, Western Australia. We are a group of passionate students who love robotics, engineering, and solving real world problems through STEM. Our team combines creativity, technical skills, and teamwork to compete in FLL robotics competitions and develop innovative solutions to challenges that matter. Through FIRST LEGO League, we learn to design, build, and program autonomous robots while researching real world issues and presenting our ideas to judges and the community. Every season, we work together to improve our robot, refine our Innovation Project, and grow as engineers, researchers, and teammates.",
  "home.about.mission.title": "Our Mission",
  "home.about.mission.desc": "Our mission is to learn, build, and innovate through teamwork. We use robotics and science to solve real problems and grow our skills. Together, we support each other and strive to make a positive impact.",
  "home.awards.title": "2025 Award Winners",
  "home.awards.desc": "Recognised for innovation and excellence in FIRST LEGO League.",
  "home.awards.innovation.title": "Innovation Award",
  "home.awards.innovation.desc": "Forrestfield Regional Competition",
  "home.awards.nationals.title": "2nd Place Innovation Award",
  "home.awards.nationals.desc": "Nationals West Competition",
  "home.whataido.title": "What We Do",
  "home.whataido.desc": "Billistic Beaniez is a FIRST LEGO League robotics team from Perth, WA. We design, build, program, research, and compete.",
  "home.whataido.robot.title": "Robot Design & Programming",
  "home.whataido.robot.desc": "We design, build, and program a LEGO robot to complete autonomous missions on the FLL competition field. Our robot uses sensors, motors, and custom code to navigate challenges with precision and reliability.",
  "home.whataido.innovation.title": "Innovation Project",
  "home.whataido.innovation.desc": "We research real world problems and develop creative solutions as part of the FLL Innovation Project. Our team investigates real challenges, experiments with ideas, and presents our findings to experts and the community.",
  "home.whataido.values.title": "Core Values",
  "home.whataido.values.desc": "We practice discovery, inclusion, teamwork, and fun, the FLL Core Values that guide our team. These values shape how we work together, solve problems, and support each other through every challenge.",
  "home.explore.title": "Explore More",
  "home.explore.desc": "Learn more about our team, robot, and FIRST LEGO League journey.",
  "home.explore.updates.title": "Project Updates",
  "home.explore.updates.desc": "Follow our progress with regular updates on build sessions, experiments, and competition preparation.",
  "home.explore.feedback.title": "Innovation Feedback",
  "home.explore.feedback.desc": "Read feedback from judges, mentors, and the community on our Innovation Project.",
  "home.explore.photos.title": "Photo Logs",
  "home.explore.photos.desc": "See our journey visually through build sessions, team meetings, and competitions.",
  "home.explore.dashboard.title": "Live Dashboard",
  "home.explore.dashboard.desc": "Watch real time sensor data from our experiments and robot testing.",
  "home.cta.title": "Follow Our FLL Journey",
  "home.cta.desc": "Follow Billistic Beaniez as we build, learn, and compete in FIRST LEGO League robotics competitions.",
  "home.cta.button": "Get in Touch",
  "robot.hero.title": "Our FIRST LEGO League Robot",
  "robot.hero.desc": "The robot we designed and built for FIRST LEGO League competition, engineered for precision, reliability, and mission success.",
  "robot.name.title": "Robot Name",
  "robot.name.value": "Tide Turner",
  "robot.name.desc": "Our FLL competition robot, designed and built by Billistic Beaniez for the FIRST LEGO League season.",
  "robot.whatis.title": "What It Does",
  "robot.whatis.desc": "Tide Turner is designed to complete FLL competition missions with precision and reliability. The robot navigates the field autonomously, using sensors and pre-programmed routines to complete missions within the 2.5 minute time limit.",
  "robot.programming.title": "Programming Highlights",
  "robot.challenges.title": "Challenges and Improvements",
  "robot.image": "",
  "innovation.hero.title": "Our Innovation Project",
  "innovation.hero.desc": "The research behind our FLL Innovation Project and why it matters for solving real world challenges.",
  "innovation.problem.title": "The Problem",
  "innovation.problem.desc": "Carbon dioxide (CO2) levels in Earth's atmosphere are rising, causing global temperatures to increase. Oceans absorb about 30% of the CO2 we release, but this comes at a cost: dissolved CO2 makes ocean water more acidic, harming marine ecosystems.",
  "innovation.hypothesis.title": "Our Hypothesis",
  "innovation.hypothesis.desc": "If we add seaweed and phytoplankton to saltwater, then the dissolved CO2 level will decrease significantly compared to a control tank, because these organisms absorb CO2 through photosynthesis.",
  "innovation.solution.title": "Our Solution",
  "innovation.solution.desc": "We use seaweed (a natural photosynthesizer) to absorb dissolved CO2 from ocean water in a controlled, measurable setup.",
  "innovation.science.title": "How Photosynthesis Helps",
  "innovation.science.desc": "Seaweed and phytoplankton perform photosynthesis just like land plants. They absorb dissolved CO2 from the water and use sunlight to produce energy and release oxygen.",
  "innovation.setup.title": "Experiment Setup",
  "innovation.sensors.title": "Sensors Used",
  "innovation.timeline.title": "Experiment Timeline",
  "innovation.results.title": "Results Summary",
  "innovation.impact.title": "Why It Matters",
  "innovation.future.title": "Future Improvements",
  "team.hero.title": "Meet the Billistic Beaniez Team",
  "team.hero.desc": "Six passionate students from Perth, WA working together to solve real world problems through FIRST LEGO League robotics and innovation.",
  "team.photo.title": "Team Photo",
  "values.hero.title": "FLL Core Values",
  "values.hero.desc": "The FIRST LEGO League Core Values that guide our team, shape our experience, and define who we are as people and learners.",
  "values.closing.title": "More Than Just Robots",
  "values.closing.desc": "While FLL is about building robots and solving challenges, the Core Values remind us that how we work together matters just as much as what we build.",
  "updates.hero.title": "Project Updates",
  "updates.hero.desc": "Follow the Billistic Beaniez FLL team's progress with updates on our robot, Innovation Project, and competition preparation.",
  "updates.empty.title": "No updates yet",
  "updates.empty.desc": "Check back soon for updates on our FIRST LEGO League journey.",
  "feedback.hero.title": "Innovation Feedback",
  "feedback.hero.desc": "Feedback and insights from the community on our FLL Innovation Project.",
  "feedback.empty.title": "No feedback yet",
  "feedback.empty.desc": "Check back soon for feedback from experts and the community.",
  "photos.hero.title": "Photo Log",
  "photos.hero.desc": "A visual timeline of Billistic Beaniez through build sessions, experiments, and FLL competitions.",
  "photos.robot.title": "Robot Photos",
  "photos.innovation.title": "Innovation Photos",
  "photos.team.title": "Team Photos",
  "photos.corevalues.title": "Core Values Photos",
  "photos.competition.title": "Competition Photos",
  "contact.hero.title": "Contact Us",
  "contact.hero.desc": "Get in touch with the Billistic Beaniez FIRST LEGO League team from Perth, WA. We welcome questions about our robotics, engineering, and Innovation Project.",
  "contact.form.name": "Your Name",
  "contact.form.email": "Email Address",
  "contact.form.message": "Your Message",
  "contact.form.button": "Send Message",
  "contact.success.title": "Message Sent",
  "contact.success.desc": "Thanks for reaching out to Billistic Beaniez. We will get back to you soon.",
  "history.hero.title": "Our FLL Journey",
  "history.hero.desc": "The story of Billistic Beaniez, our development through seasons of FIRST LEGO League robotics, learning, and growth.",
};
