export const defaults: Record<string, string> = {
  "site.logo": "",
  "home.hero.title": "Billistic Beaniez Robotics & STEM",
  "home.hero.subtitle": "Billistic Beaniez | FLL Team",
  "home.hero.description": "Our mission is to learn, build, and innovate through teamwork. We use robotics and science to solve real problems and grow our skills. Together, we support each other and strive to make a positive impact.",
  "home.hero.button1": "See Our Innovation",
  "home.hero.button2": "See Our Robot",
  "home.whataido.title": "What We Do",
  "home.whataido.desc": "Three pillars that make up our FLL journey.",
  "home.whataido.robot.title": "Robot",
  "home.whataido.robot.desc": "We design, build, and program a LEGO robot to complete autonomous missions on the competition field.",
  "home.whataido.innovation.title": "Innovation",
  "home.whataido.innovation.desc": "We research real world problems and develop creative solutions. Our current project uses seaweed to remove CO2 from ocean water.",
  "home.whataido.values.title": "Team Values",
  "home.whataido.values.desc": "We practice discovery, inclusion, teamwork, and fun while learning to work together and make a positive impact.",
  "home.explore.title": "Explore More",
  "home.explore.desc": "Dive deeper into our project and team.",
  "home.cta.title": "Join Us on Our Journey",
  "home.cta.desc": "Follow Billistic Beaniez as we build, learn, and compete in FIRST LEGO League.",
  "home.cta.button": "Get in Touch",
  "robot.hero.title": "Meet Our Robot",
  "robot.hero.desc": "The engineering marvel that brings our ideas to life on the competition field.",
  "robot.name.title": "Robot Name",
  "robot.name.value": "Tide Turner",
  "robot.name.desc": "Inspired by our ocean science theme, Tide Turner represents our mission to turn the tide on climate change through innovative robotics and engineering.",
  "robot.whatis.title": "What It Does",
  "robot.whatis.desc": "Tide Turner is designed to complete FLL competition missions with precision and reliability. The robot navigates the field autonomously, using a combination of sensors and pre-programmed routines to complete as many missions as possible within the 2.5 minute time limit.",
  "robot.programming.title": "Programming Highlights",
  "robot.challenges.title": "Challenges and Improvements",
  "robot.image": "",
  "innovation.hero.title": "Innovation Project",
  "innovation.hero.desc": "The research behind our experiment and why removing CO2 from ocean water matters for climate change.",
  "innovation.problem.title": "The Problem",
  "innovation.problem.desc": "Carbon dioxide (CO2) levels in Earth's atmosphere are rising, causing global temperatures to increase. Oceans absorb about 30% of the CO2 we release, but this comes at a cost: dissolved CO2 makes ocean water more acidic, harming marine ecosystems.",
  "innovation.hypothesis.title": "Our Hypothesis",
  "innovation.hypothesis.desc": "If we add seaweed and phytoplankton to saltwater, then the dissolved CO2 level will decrease significantly compared to a control tank, because these organisms absorb CO2 through photosynthesis.",
  "innovation.solution.title": "Our Solution",
  "innovation.solution.desc": "We use seaweed (a natural photosynthesizer) to absorb dissolved CO2 from ocean water in a controlled, measurable setup.",
  "innovation.science.title": "How Photosynthesis Helps",
  "innovation.science.desc": "Seaweed and phytoplankton perform photosynthesis just like land plants. They absorb dissolved CO2 from the water and use sunlight to produce energy and release oxygen.",
  "innovation.setup.title": "Experiment Setup",
  "innovation.sensors.title": "Sensors Used",
  "innovation.timeline.title": "Experiment Timeline",
  "innovation.results.title": "Results Summary",
  "innovation.impact.title": "Why It Matters",
  "innovation.future.title": "Future Improvements",
  "team.hero.title": "Meet the Team",
  "team.hero.desc": "Six passionate students working together to solve real world problems through robotics and innovation.",
  "team.photo.title": "Team Photo",
  "values.hero.title": "FLL Core Values",
  "values.hero.desc": "The principles that guide our team, shape our experience, and define who we are as people and learners.",
  "values.closing.title": "More Than Just Robots",
  "values.closing.desc": "While FLL is about building robots and solving challenges, the Core Values remind us that how we work together matters just as much as what we build.",
  "updates.hero.title": "Project Updates",
  "updates.hero.desc": "Follow our experiment progress over time.",
  "updates.empty.title": "No updates yet",
  "updates.empty.desc": "Check back soon for experiment progress.",
  "feedback.hero.title": "Feedback We Have Received",
  "feedback.hero.desc": "What people are saying about our project.",
  "feedback.empty.title": "No feedback yet",
  "feedback.empty.desc": "Check back soon for feedback from the community.",
  "photos.hero.title": "Photo Log",
  "photos.hero.desc": "A visual timeline of our experiment and team activities.",
  "photos.robot.title": "Robot Photos",
  "photos.innovation.title": "Innovation Photos",
  "photos.team.title": "Team Photos",
  "photos.corevalues.title": "Core Values Photos",
  "photos.competition.title": "Competition Photos",
  "contact.hero.title": "Contact Us",
  "contact.hero.desc": "Get in touch with the Billistic Beaniez team.",
  "contact.form.name": "Your Name",
  "contact.form.email": "Email Address",
  "contact.form.message": "Your Message",
  "contact.form.button": "Send Message",
  "contact.success.title": "Message Sent",
  "contact.success.desc": "Thanks for reaching out. We will get back to you soon.",
  "history.hero.title": "Team History",
  "history.hero.desc": "Our journey through the years of FIRST LEGO League.",
};
