allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  better-sqlite3: true
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  sharp: false
  unrs-resolver: false
  workerd: set this to true or false
